### PR TITLE
Fixed the regression in addChildNodes

### PR DESCRIPTION
**Pull request by acierto**
Hey,
I found one more regression introduced in v0.14.*

Currently the issue in the *addChildNodes*.
If you call *addChildNodes* it will append children and open them immediately, regardless of the status of the parent node, was it opened or not.

That leads to a broken state of the tree. Those nodes which user see are not usable anymore, and when you click on parent toggler these nodes will be duplicated and you can operate only with them.

### CODE REVIEW

**Comment by cheton** [comment]
The "if" statement should handle only **this.nodes** and **this.rows**, so the parent node will have chance to update content after adding new child nodes. For example, assume that there is a label  aside the parent node, showing the number of its child nodes.

image


```js
if (parentOffset >= 0) {
    if (parentNode.state.open === true) {
        // Update nodes & rows
        this.nodes.splice.apply(this.nodes, [parentOffset + 1, deleteCount].concat(nodes));
        this.rows.splice.apply(this.rows, [parentOffset + 1, deleteCount].concat(rows));
    }

    // Update the row corresponding to the parent node
    this.rows[parentOffset] = this.options.rowRenderer(parentNode, this.options);
}
```

**Comment by acierto** [comment]
Yes you are right, applied a feedback!

**Comment by acierto** [comment]
Would be it possible to release a new version today based on this fix? 
As we have a release tomorrow, a bit critical for us.

**Comment by cheton** [comment]
Sure! I will publish a release soon.

**Comment by cheton** [comment]
Published v1.14.7

**Pull request merged**
